import Head from "next/head";
import styles from "../styles/Home.module.css";
import LinkCard from "../components/LinkCard";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <LinkCard
            cardTitle="Learn &rarr;"
            cardContent="Learn about Next.js in an interactive course with quizzes!"
            linkTo="https://nextjs.org/learn"
          />
          <LinkCard
            cardTitle="Documentation &rarr;"
            cardContent="Find in-depth information about Next.js features and API."
            linkTo="https://nextjs.org/docs"
          />
          <LinkCard
            cardTitle="Examples &rarr;"
            cardContent="Discover and deploy boilerplate example Next.js projects."
            linkTo="https://github.com/vercel/next.js/tree/canary/examples"
          />
          <LinkCard
            cardTitle="Deploy &rarr;"
            cardContent="Instantly deploy your Next.js site to a public URL with Vercel."
            linkTo="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          />
        </div>
        <Footer />
      </main>
    </div>
  );
}
